begin;

create schema if not exists private;
revoke all on schema private from public;

create table public.profiles (
	id uuid primary key references auth.users (id) on delete cascade,
	full_name text not null default '',
	email text not null unique,
	role text not null default 'viewer' check (role in ('owner', 'admin', 'sales', 'viewer')),
	status text not null default 'invited' check (status in ('invited', 'active', 'suspended')),
	timezone text not null default 'UTC' check (length(trim(timezone)) > 0),
	created_at timestamptz not null default now(),
	updated_at timestamptz not null default now()
);

create table public.app_settings (
	setting_key text primary key check (length(trim(setting_key)) > 0),
	setting_value jsonb not null default '{}'::jsonb,
	description text,
	updated_by uuid references public.profiles (id) on delete set null,
	created_at timestamptz not null default now(),
	updated_at timestamptz not null default now(),
	constraint app_settings_no_secrets check (
		setting_key !~* '(secret|password|service[_-]?role|client[_-]?secret|webhook[_-]?secret)'
	)
);

create table public.lead_sources (
	id uuid primary key default gen_random_uuid(),
	code text not null unique check (code ~ '^[a-z][a-z0-9_]*$'),
	label text not null check (length(trim(label)) > 0),
	active boolean not null default true,
	sort_order integer not null default 0 check (sort_order >= 0),
	created_at timestamptz not null default now(),
	updated_at timestamptz not null default now()
);

create table public.lost_reasons (
	id uuid primary key default gen_random_uuid(),
	code text not null unique check (code ~ '^[a-z][a-z0-9_]*$'),
	label text not null check (length(trim(label)) > 0),
	active boolean not null default true,
	sort_order integer not null default 0 check (sort_order >= 0),
	created_at timestamptz not null default now(),
	updated_at timestamptz not null default now()
);

create table public.clients (
	id uuid primary key default gen_random_uuid(),
	client_number bigint generated by default as identity unique,
	type text not null check (type in ('individual', 'company')),
	display_name text not null check (length(trim(display_name)) > 0),
	company_name text,
	email text,
	phone text,
	billing_address text,
	status text not null default 'active' check (status in ('active', 'inactive', 'archived')),
	source_lead_id uuid unique,
	converted_at timestamptz,
	created_at timestamptz not null default now(),
	updated_at timestamptz not null default now()
);

create table public.leads (
	id uuid primary key default gen_random_uuid(),
	lead_number bigint generated by default as identity unique,
	source_id uuid references public.lead_sources (id) on delete set null,
	external_submission_id text unique,
	first_name text not null check (length(trim(first_name)) > 0),
	last_name text not null default '',
	email text,
	phone text,
	company text,
	message text,
	landing_page text,
	referrer text,
	utm_source text,
	utm_medium text,
	utm_campaign text,
	utm_content text,
	utm_term text,
	pipeline_stage text not null default 'NEW' check (pipeline_stage in ('NEW', 'QUALIFICATION', 'PROPOSAL', 'DECISION', 'WON', 'LOST')),
	attention_state text not null default 'none' check (attention_state in ('none', 'waiting_on_client', 'waiting_on_us', 'follow_up_scheduled', 'paused')),
	assigned_to uuid references public.profiles (id) on delete set null,
	lost_reason_id uuid references public.lost_reasons (id) on delete restrict,
	lost_notes text,
	converted_client_id uuid references public.clients (id) on delete set null,
	last_activity_at timestamptz,
	lock_version bigint not null default 1 check (lock_version > 0),
	created_at timestamptz not null default now(),
	updated_at timestamptz not null default now(),
	constraint leads_loss_reason_matches_stage check (
		(pipeline_stage = 'LOST' and lost_reason_id is not null) or
		(pipeline_stage <> 'LOST' and lost_reason_id is null)
	)
);

alter table public.clients
	add constraint clients_source_lead_id_fkey
	foreign key (source_lead_id) references public.leads (id) on delete set null;

create table public.client_contacts (
	id uuid primary key default gen_random_uuid(),
	client_id uuid not null references public.clients (id) on delete cascade,
	first_name text not null check (length(trim(first_name)) > 0),
	last_name text not null default '',
	email text,
	phone text,
	job_title text,
	is_primary boolean not null default false,
	created_at timestamptz not null default now(),
	updated_at timestamptz not null default now()
);

create table public.quotes (
	id uuid primary key default gen_random_uuid(),
	base_quote_number bigint generated by default as identity,
	revision_number integer not null default 1 check (revision_number > 0),
	lead_id uuid not null references public.leads (id) on delete restrict,
	client_id uuid references public.clients (id) on delete restrict,
	status text not null default 'draft' check (status in ('draft', 'ready', 'sent', 'accepted', 'declined', 'expired', 'cancelled', 'superseded')),
	currency text not null default 'ZAR' check (currency ~ '^[A-Z]{3}$'),
	subject text not null check (length(trim(subject)) > 0),
	introduction text,
	terms text,
	tax_label text,
	tax_rate numeric(7, 4) not null default 0 check (tax_rate >= 0),
	subtotal numeric(14, 2) not null default 0 check (subtotal >= 0),
	tax_amount numeric(14, 2) not null default 0 check (tax_amount >= 0),
	total numeric(14, 2) not null default 0 check (total >= 0),
	valid_until date,
	ready_at timestamptz,
	sent_at timestamptz,
	accepted_at timestamptz,
	declined_at timestamptz,
	expired_at timestamptz,
	supersedes_quote_id uuid references public.quotes (id) on delete restrict,
	document_path text,
	document_hash text,
	created_by uuid not null references public.profiles (id) on delete restrict,
	lock_version bigint not null default 1 check (lock_version > 0),
	created_at timestamptz not null default now(),
	updated_at timestamptz not null default now(),
	unique (base_quote_number, revision_number)
);

create table public.quote_items (
	id uuid primary key default gen_random_uuid(),
	quote_id uuid not null references public.quotes (id) on delete cascade,
	position integer not null check (position > 0),
	name text not null check (length(trim(name)) > 0),
	description text,
	quantity numeric(14, 4) not null check (quantity > 0),
	unit_price numeric(14, 2) not null check (unit_price >= 0),
	taxable boolean not null default true,
	line_subtotal numeric(14, 2) not null check (line_subtotal >= 0),
	created_at timestamptz not null default now(),
	updated_at timestamptz not null default now(),
	unique (quote_id, position)
);

create table public.tasks (
	id uuid primary key default gen_random_uuid(),
	lead_id uuid references public.leads (id) on delete cascade,
	client_id uuid references public.clients (id) on delete cascade,
	quote_id uuid references public.quotes (id) on delete cascade,
	type text not null check (type in ('review_lead', 'call_client', 'prepare_quote', 'send_quote', 'follow_up', 'confirm_acceptance', 'custom')),
	title text not null check (length(trim(title)) > 0),
	description text,
	assigned_to uuid references public.profiles (id) on delete set null,
	status text not null default 'open' check (status in ('open', 'completed', 'cancelled')),
	due_at timestamptz,
	completed_at timestamptz,
	cancelled_at timestamptz,
	notification_sent_at timestamptz,
	created_by uuid not null references public.profiles (id) on delete restrict,
	created_at timestamptz not null default now(),
	updated_at timestamptz not null default now(),
	constraint tasks_have_parent check (lead_id is not null or client_id is not null or quote_id is not null)
);

create table public.outbound_messages (
	id uuid primary key default gen_random_uuid(),
	lead_id uuid references public.leads (id) on delete set null,
	client_id uuid references public.clients (id) on delete set null,
	quote_id uuid references public.quotes (id) on delete set null,
	channel text not null check (channel in ('email')),
	purpose text not null check (length(trim(purpose)) > 0),
	provider text not null default 'sendpulse' check (provider = 'sendpulse'),
	recipient_snapshot jsonb not null default '{}'::jsonb,
	subject text,
	provider_message_id text,
	delivery_status text not null default 'pending' check (delivery_status in ('pending', 'sending', 'submitted', 'delivered', 'bounced', 'failed')),
	attempt_count integer not null default 0 check (attempt_count >= 0),
	last_error text,
	submitted_at timestamptz,
	delivered_at timestamptz,
	bounced_at timestamptz,
	created_at timestamptz not null default now(),
	updated_at timestamptz not null default now()
);

create table public.message_events (
	id uuid primary key default gen_random_uuid(),
	outbound_message_id uuid not null references public.outbound_messages (id) on delete cascade,
	provider_event_id text,
	event_type text not null check (length(trim(event_type)) > 0),
	occurred_at timestamptz not null,
	metadata jsonb not null default '{}'::jsonb,
	deduplication_hash text not null unique,
	created_at timestamptz not null default now(),
	unique (provider_event_id)
);

create table public.inbound_submissions (
	id uuid primary key default gen_random_uuid(),
	source text not null check (length(trim(source)) > 0),
	external_submission_id text not null check (length(trim(external_submission_id)) > 0),
	form_id text,
	intake_state text not null default 'received' check (intake_state in ('received', 'accepted', 'duplicate', 'rejected', 'failed')),
	payload_hash text not null,
	lead_id uuid references public.leads (id) on delete set null,
	error_message text,
	received_at timestamptz not null default now(),
	processed_at timestamptz,
	unique (source, external_submission_id)
);

create table public.activities (
	id uuid primary key default gen_random_uuid(),
	lead_id uuid references public.leads (id) on delete cascade,
	client_id uuid references public.clients (id) on delete cascade,
	quote_id uuid references public.quotes (id) on delete cascade,
	task_id uuid references public.tasks (id) on delete cascade,
	outbound_message_id uuid references public.outbound_messages (id) on delete cascade,
	actor_id uuid references public.profiles (id) on delete set null,
	event_type text not null check (length(trim(event_type)) > 0),
	occurred_at timestamptz not null default now(),
	metadata jsonb not null default '{}'::jsonb,
	summary text not null check (length(trim(summary)) > 0),
	created_at timestamptz not null default now(),
	constraint activities_have_target check (
		lead_id is not null or client_id is not null or quote_id is not null or task_id is not null or outbound_message_id is not null
	)
);

create index leads_pipeline_stage_idx on public.leads (pipeline_stage, updated_at desc);
create index leads_attention_state_idx on public.leads (attention_state, updated_at desc);
create index leads_assigned_to_idx on public.leads (assigned_to, updated_at desc);
create index leads_lost_reason_idx on public.leads (lost_reason_id) where lost_reason_id is not null;
create index client_contacts_client_id_idx on public.client_contacts (client_id);
create unique index client_contacts_one_primary_idx on public.client_contacts (client_id) where is_primary;
create index quotes_lead_status_idx on public.quotes (lead_id, status, updated_at desc);
create index quotes_client_status_idx on public.quotes (client_id, status, updated_at desc) where client_id is not null;
create index quote_items_quote_id_idx on public.quote_items (quote_id, position);
create index tasks_open_due_idx on public.tasks (status, due_at) where status = 'open';
create index tasks_assigned_to_idx on public.tasks (assigned_to, status, due_at) where assigned_to is not null;
create index activities_lead_occurred_idx on public.activities (lead_id, occurred_at desc) where lead_id is not null;
create index activities_client_occurred_idx on public.activities (client_id, occurred_at desc) where client_id is not null;
create index outbound_messages_quote_idx on public.outbound_messages (quote_id, created_at desc) where quote_id is not null;
create index message_events_message_idx on public.message_events (outbound_message_id, occurred_at desc);
create index inbound_submissions_lead_idx on public.inbound_submissions (lead_id) where lead_id is not null;

create function private.has_active_profile()
returns boolean
language sql
stable
security definer
set search_path = pg_catalog, public
as $$
	select exists (
		select 1
		from public.profiles
		where id = (select auth.uid())
		  and status = 'active'
	);
$$;

create function private.has_any_role(allowed_roles text[])
returns boolean
language sql
stable
security definer
set search_path = pg_catalog, public
as $$
	select exists (
		select 1
		from public.profiles
		where id = (select auth.uid())
		  and status = 'active'
		  and role = any (allowed_roles)
	);
$$;

create function private.current_user_role()
returns text
language sql
stable
security definer
set search_path = pg_catalog, public
as $$
	select role
	from public.profiles
	where id = (select auth.uid())
	  and status = 'active'
	limit 1;
$$;

create function private.set_updated_at()
returns trigger
language plpgsql
set search_path = pg_catalog, public
as $$
begin
	new.updated_at = now();
	return new;
end;
$$;

create function private.set_setting_actor()
returns trigger
language plpgsql
set search_path = pg_catalog, public
as $$
begin
	if (select private.has_active_profile()) then
		new.updated_by = (select auth.uid());
	end if;
	return new;
end;
$$;

create function private.validate_lead_loss()
returns trigger
language plpgsql
set search_path = pg_catalog, public
as $$
declare
	lost_reason_code text;
begin
	if new.pipeline_stage = 'LOST' then
		select code into lost_reason_code
		from public.lost_reasons
		where id = new.lost_reason_id and active;
		if lost_reason_code is null then
			raise exception using errcode = '23514', message = 'LOST leads require an active lost reason';
		end if;
		if lost_reason_code = 'other' and length(trim(coalesce(new.lost_notes, ''))) = 0 then
			raise exception using errcode = '23514', message = 'The other lost reason requires lost_notes';
		end if;
	end if;
	return new;
end;
$$;

create function private.enforce_lock_version()
returns trigger
language plpgsql
set search_path = pg_catalog, public
as $$
begin
	if new.lock_version <> old.lock_version + 1 then
		raise exception using
			errcode = '40001',
			message = format('stale or invalid lock_version for %s', tg_table_name);
	end if;
	return new;
end;
$$;

create function private.protect_profile_privileges()
returns trigger
language plpgsql
set search_path = pg_catalog, public
as $$
declare
	actor_role text;
begin
	if current_user in ('postgres', 'service_role', 'supabase_admin') then
		return new;
	end if;
	if new.id is distinct from old.id or new.email is distinct from old.email then
		raise exception using errcode = '42501', message = 'Profile identity fields are Auth-managed';
	end if;
	actor_role = private.current_user_role();
	if actor_role is null then
		raise exception using errcode = '42501', message = 'An active profile is required';
	end if;
	if actor_role <> 'owner' and (
		new.role is distinct from old.role or new.status is distinct from old.status
	) then
		raise exception using errcode = '42501', message = 'Only the owner may change profile role or status';
	end if;
	return new;
end;
$$;

create function private.protect_quote_immutability()
returns trigger
language plpgsql
set search_path = pg_catalog, public
as $$
begin
	if old.status in ('sent', 'accepted', 'declined', 'expired', 'cancelled', 'superseded') and (
		new.lead_id is distinct from old.lead_id or
		new.client_id is distinct from old.client_id or
		new.currency is distinct from old.currency or
		new.subject is distinct from old.subject or
		new.introduction is distinct from old.introduction or
		new.terms is distinct from old.terms or
		new.tax_label is distinct from old.tax_label or
		new.tax_rate is distinct from old.tax_rate or
		new.subtotal is distinct from old.subtotal or
		new.tax_amount is distinct from old.tax_amount or
		new.total is distinct from old.total or
		new.valid_until is distinct from old.valid_until or
		new.document_path is distinct from old.document_path or
		new.document_hash is distinct from old.document_hash
	) then
		raise exception using errcode = '55000', message = 'Sent quote commercial data is immutable';
	end if;
	return new;
end;
$$;

create function private.prevent_activity_mutation()
returns trigger
language plpgsql
set search_path = pg_catalog, public
as $$
begin
	raise exception using errcode = '55000', message = 'Activity is append-only';
end;
$$;

create function private.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
begin
	insert into public.profiles (id, email, full_name, role, status)
	values (
		new.id,
		coalesce(new.email, ''),
		coalesce(new.raw_user_meta_data ->> 'full_name', ''),
		'viewer',
		'invited'
	)
	on conflict (id) do update set email = excluded.email;
	return new;
end;
$$;

create function private.handle_user_update()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
begin
	update public.profiles
	set email = coalesce(new.email, profiles.email),
		full_name = coalesce(new.raw_user_meta_data ->> 'full_name', profiles.full_name)
	where id = new.id;
	return new;
end;
$$;

grant usage on schema private to authenticated;
grant execute on function private.has_active_profile() to authenticated;
grant execute on function private.has_any_role(text[]) to authenticated;
grant execute on function private.current_user_role() to authenticated;
grant execute on function private.set_updated_at() to authenticated;
grant execute on function private.set_setting_actor() to authenticated;
grant execute on function private.validate_lead_loss() to authenticated;
grant execute on function private.enforce_lock_version() to authenticated;
grant execute on function private.protect_profile_privileges() to authenticated;
grant execute on function private.protect_quote_immutability() to authenticated;
grant execute on function private.prevent_activity_mutation() to authenticated;

do $$
begin
	if exists (select 1 from pg_roles where rolname = 'supabase_auth_admin') then
		execute 'grant usage on schema private to supabase_auth_admin';
		execute 'grant execute on function private.handle_new_user() to supabase_auth_admin';
		execute 'grant execute on function private.handle_user_update() to supabase_auth_admin';
	end if;
end;
$$;

create trigger profiles_updated_at
before update on public.profiles
for each row execute function private.set_updated_at();

create trigger app_settings_updated_at
before update on public.app_settings
for each row execute function private.set_updated_at();

create trigger app_settings_actor
before insert or update on public.app_settings
for each row execute function private.set_setting_actor();

create trigger lead_sources_updated_at
before update on public.lead_sources
for each row execute function private.set_updated_at();

create trigger lost_reasons_updated_at
before update on public.lost_reasons
for each row execute function private.set_updated_at();

create trigger clients_updated_at
before update on public.clients
for each row execute function private.set_updated_at();

create trigger leads_updated_at
before update on public.leads
for each row execute function private.set_updated_at();

create trigger leads_loss_validation
before insert or update on public.leads
for each row execute function private.validate_lead_loss();

create trigger leads_lock_version
before update on public.leads
for each row execute function private.enforce_lock_version();

create trigger client_contacts_updated_at
before update on public.client_contacts
for each row execute function private.set_updated_at();

create trigger quotes_updated_at
before update on public.quotes
for each row execute function private.set_updated_at();

create trigger quotes_lock_version
before update on public.quotes
for each row execute function private.enforce_lock_version();

create trigger quotes_immutability
before update on public.quotes
for each row execute function private.protect_quote_immutability();

create trigger quote_items_updated_at
before update on public.quote_items
for each row execute function private.set_updated_at();

create trigger tasks_updated_at
before update on public.tasks
for each row execute function private.set_updated_at();

create trigger outbound_messages_updated_at
before update on public.outbound_messages
for each row execute function private.set_updated_at();

create trigger activities_append_only
before update or delete on public.activities
for each row execute function private.prevent_activity_mutation();

create trigger profiles_privilege_protection
before update on public.profiles
for each row execute function private.protect_profile_privileges();

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function private.handle_new_user();

drop trigger if exists on_auth_user_updated on auth.users;
create trigger on_auth_user_updated
after update of email, raw_user_meta_data on auth.users
for each row execute function private.handle_user_update();

insert into public.profiles (id, email, full_name, role, status)
select
	id,
	coalesce(email, ''),
	coalesce(raw_user_meta_data ->> 'full_name', ''),
	'viewer',
	'invited'
from auth.users
on conflict (id) do nothing;

do $$
declare
	table_name text;
begin
	foreach table_name in array ARRAY[
		'profiles', 'app_settings', 'lead_sources', 'lost_reasons', 'leads', 'clients',
		'client_contacts', 'quotes', 'quote_items', 'tasks', 'activities',
		'outbound_messages', 'message_events', 'inbound_submissions'
	] loop
		execute format('alter table public.%I enable row level security', table_name);
		execute format('revoke all on table public.%I from anon, authenticated', table_name);
		execute format('grant select on table public.%I to authenticated', table_name);
	end loop;
end;
$$;

alter default privileges in schema public revoke all on tables from anon, authenticated;
alter default privileges in schema public revoke all on sequences from anon, authenticated;

grant insert, update on table public.app_settings to authenticated;
grant delete on table public.app_settings to authenticated;
grant insert, update, delete on table public.lead_sources to authenticated;
grant insert, update, delete on table public.lost_reasons to authenticated;
grant update on table public.profiles to authenticated;
grant insert, update on table public.leads to authenticated;
grant insert, update on table public.clients to authenticated;
grant insert, update on table public.client_contacts to authenticated;
grant insert, update on table public.quotes to authenticated;
grant insert, update on table public.quote_items to authenticated;
grant insert, update on table public.tasks to authenticated;
grant insert, update on table public.outbound_messages to authenticated;
grant insert on table public.activities to authenticated;

grant usage, select on sequence public.clients_client_number_seq to authenticated;
grant usage, select on sequence public.leads_lead_number_seq to authenticated;
grant usage, select on sequence public.quotes_base_quote_number_seq to authenticated;

create policy profiles_select_active
on public.profiles for select to authenticated
using ((select private.has_active_profile()));

create policy profiles_update_admin_or_owner
on public.profiles for update to authenticated
using ((select private.has_any_role(array['owner', 'admin']::text[])))
with check ((select private.has_any_role(array['owner', 'admin']::text[])));

create policy app_settings_select_active
on public.app_settings for select to authenticated
using ((select private.has_active_profile()));

create policy app_settings_insert_admin_or_owner
on public.app_settings for insert to authenticated
with check ((select private.has_any_role(array['owner', 'admin']::text[])));

create policy app_settings_update_admin_or_owner
on public.app_settings for update to authenticated
using ((select private.has_any_role(array['owner', 'admin']::text[])))
with check ((select private.has_any_role(array['owner', 'admin']::text[])));

create policy app_settings_delete_admin_or_owner
on public.app_settings for delete to authenticated
using ((select private.has_any_role(array['owner', 'admin']::text[])));

create policy lead_sources_select_active
on public.lead_sources for select to authenticated
using ((select private.has_active_profile()));

create policy lead_sources_insert_admin_or_owner
on public.lead_sources for insert to authenticated
with check ((select private.has_any_role(array['owner', 'admin']::text[])));

create policy lead_sources_update_admin_or_owner
on public.lead_sources for update to authenticated
using ((select private.has_any_role(array['owner', 'admin']::text[])))
with check ((select private.has_any_role(array['owner', 'admin']::text[])));

create policy lead_sources_delete_admin_or_owner
on public.lead_sources for delete to authenticated
using ((select private.has_any_role(array['owner', 'admin']::text[])));

create policy lost_reasons_select_active
on public.lost_reasons for select to authenticated
using ((select private.has_active_profile()));

create policy lost_reasons_insert_admin_or_owner
on public.lost_reasons for insert to authenticated
with check ((select private.has_any_role(array['owner', 'admin']::text[])));

create policy lost_reasons_update_admin_or_owner
on public.lost_reasons for update to authenticated
using ((select private.has_any_role(array['owner', 'admin']::text[])))
with check ((select private.has_any_role(array['owner', 'admin']::text[])));

create policy lost_reasons_delete_admin_or_owner
on public.lost_reasons for delete to authenticated
using ((select private.has_any_role(array['owner', 'admin']::text[])));

create policy leads_select_active
on public.leads for select to authenticated
using ((select private.has_active_profile()));

create policy leads_insert_crm_roles
on public.leads for insert to authenticated
with check ((select private.has_any_role(array['owner', 'admin', 'sales']::text[])));

create policy leads_update_crm_roles
on public.leads for update to authenticated
using ((select private.has_any_role(array['owner', 'admin', 'sales']::text[])))
with check ((select private.has_any_role(array['owner', 'admin', 'sales']::text[])));

create policy clients_select_active
on public.clients for select to authenticated
using ((select private.has_active_profile()));

create policy clients_insert_crm_roles
on public.clients for insert to authenticated
with check ((select private.has_any_role(array['owner', 'admin', 'sales']::text[])));

create policy clients_update_crm_roles
on public.clients for update to authenticated
using ((select private.has_any_role(array['owner', 'admin', 'sales']::text[])))
with check ((select private.has_any_role(array['owner', 'admin', 'sales']::text[])));

create policy client_contacts_select_active
on public.client_contacts for select to authenticated
using ((select private.has_active_profile()));

create policy client_contacts_insert_crm_roles
on public.client_contacts for insert to authenticated
with check ((select private.has_any_role(array['owner', 'admin', 'sales']::text[])));

create policy client_contacts_update_crm_roles
on public.client_contacts for update to authenticated
using ((select private.has_any_role(array['owner', 'admin', 'sales']::text[])))
with check ((select private.has_any_role(array['owner', 'admin', 'sales']::text[])));

create policy quotes_select_active
on public.quotes for select to authenticated
using ((select private.has_active_profile()));

create policy quotes_insert_crm_roles
on public.quotes for insert to authenticated
with check ((select private.has_any_role(array['owner', 'admin', 'sales']::text[])));

create policy quotes_update_crm_roles
on public.quotes for update to authenticated
using ((select private.has_any_role(array['owner', 'admin', 'sales']::text[])))
with check ((select private.has_any_role(array['owner', 'admin', 'sales']::text[])));

create policy quote_items_select_active
on public.quote_items for select to authenticated
using ((select private.has_active_profile()));

create policy quote_items_insert_crm_roles
on public.quote_items for insert to authenticated
with check ((select private.has_any_role(array['owner', 'admin', 'sales']::text[])));

create policy quote_items_update_crm_roles
on public.quote_items for update to authenticated
using ((select private.has_any_role(array['owner', 'admin', 'sales']::text[])))
with check ((select private.has_any_role(array['owner', 'admin', 'sales']::text[])));

create policy tasks_select_active
on public.tasks for select to authenticated
using ((select private.has_active_profile()));

create policy tasks_insert_crm_roles
on public.tasks for insert to authenticated
with check ((select private.has_any_role(array['owner', 'admin', 'sales']::text[])));

create policy tasks_update_crm_roles
on public.tasks for update to authenticated
using ((select private.has_any_role(array['owner', 'admin', 'sales']::text[])))
with check ((select private.has_any_role(array['owner', 'admin', 'sales']::text[])));

create policy activities_select_active
on public.activities for select to authenticated
using ((select private.has_active_profile()));

create policy activities_insert_crm_roles
on public.activities for insert to authenticated
with check (
	(select private.has_any_role(array['owner', 'admin', 'sales']::text[]))
	and actor_id = (select auth.uid())
);

create policy outbound_messages_select_active
on public.outbound_messages for select to authenticated
using ((select private.has_active_profile()));

create policy outbound_messages_insert_crm_roles
on public.outbound_messages for insert to authenticated
with check ((select private.has_any_role(array['owner', 'admin', 'sales']::text[])));

create policy outbound_messages_update_crm_roles
on public.outbound_messages for update to authenticated
using ((select private.has_any_role(array['owner', 'admin', 'sales']::text[])))
with check ((select private.has_any_role(array['owner', 'admin', 'sales']::text[])));

create policy message_events_select_active
on public.message_events for select to authenticated
using ((select private.has_active_profile()));

create policy inbound_submissions_select_active
on public.inbound_submissions for select to authenticated
using ((select private.has_active_profile()));

commit;
