begin;

-- v1.4.0 is a forward-only persistence extension. Historical v1.3.2
-- migrations remain unchanged; every new lifecycle write goes through a
-- trusted action below.

alter table public.leads
	add column if not exists qualification_notes text,
	add column if not exists qualification_started_at timestamptz,
	add column if not exists qualified_at timestamptz;

alter table public.leads
	drop constraint if exists leads_qualification_timestamps_valid,
	add constraint leads_qualification_timestamps_valid check (
		qualified_at is null
		or (qualification_started_at is not null and qualified_at >= qualification_started_at)
	);

alter table public.leads
	drop constraint if exists leads_qualification_notes_bounds,
	add constraint leads_qualification_notes_bounds check (
		qualification_notes is null or char_length(qualification_notes) <= 10000
	);

create table if not exists public.fulfilment_cases (
	id uuid primary key default gen_random_uuid(),
	fulfilment_number bigint generated by default as identity unique,
	client_id uuid not null references public.clients (id) on delete restrict,
	lead_id uuid not null references public.leads (id) on delete restrict,
	accepted_quote_id uuid not null references public.quotes (id) on delete restrict,
	status text not null default 'open' check (status in ('open', 'completed', 'cancelled')),
	created_at timestamptz not null default now(),
	updated_at timestamptz not null default now(),
	completed_at timestamptz,
	cancelled_at timestamptz,
	cancel_reason text,
	lock_version bigint not null default 1 check (lock_version > 0),
	constraint fulfilment_cases_lifecycle_timestamps check (
		(status = 'open' and completed_at is null and cancelled_at is null and cancel_reason is null)
		or (status = 'completed' and completed_at is not null and cancelled_at is null and cancel_reason is null)
		or (status = 'cancelled' and completed_at is null and cancelled_at is not null and length(trim(coalesce(cancel_reason, ''))) > 0)
	),
	constraint fulfilment_cases_input_bounds check (
		cancel_reason is null or char_length(cancel_reason) <= 2000
	)
);

create table if not exists public.fulfilment_steps (
	id uuid primary key default gen_random_uuid(),
	fulfilment_case_id uuid not null references public.fulfilment_cases (id) on delete cascade,
	type text not null check (type in ('installation', 'courier', 'pickup')),
	status text not null,
	scheduled_for timestamptz,
	completed_at timestamptz,
	tracking_reference text,
	notes text,
	created_at timestamptz not null default now(),
	updated_at timestamptz not null default now(),
	lock_version bigint not null default 1 check (lock_version > 0),
	cancelled_at timestamptz,
	cancel_reason text,
	constraint fulfilment_steps_state_shape check (
		(type = 'installation' and status in ('awaiting_schedule', 'scheduled', 'completed', 'cancelled'))
		or (type = 'courier' and status in ('awaiting_dispatch', 'dispatched', 'delivered', 'cancelled'))
		or (type = 'pickup' and status in ('preparing', 'ready_for_collection', 'collected', 'cancelled'))
	),
	constraint fulfilment_steps_terminal_evidence check (
		(
			status in ('completed', 'delivered', 'collected')
			and completed_at is not null
			and cancelled_at is null
			and cancel_reason is null
		)
		or (
			status = 'cancelled'
			and completed_at is null
			and cancelled_at is not null
			and length(trim(coalesce(cancel_reason, ''))) > 0
		)
		or (
			status not in ('completed', 'delivered', 'collected', 'cancelled')
			and completed_at is null
			and cancelled_at is null
			and cancel_reason is null
		)
	),
	constraint fulfilment_steps_scheduled_evidence check (
		type <> 'installation'
		or status in ('awaiting_schedule', 'cancelled')
		or scheduled_for is not null
	),
	constraint fulfilment_steps_input_bounds check (
		(tracking_reference is null or char_length(tracking_reference) <= 500)
		and (notes is null or char_length(notes) <= 10000)
		and (cancel_reason is null or char_length(cancel_reason) <= 2000)
	)
);

create table if not exists public.payment_milestones (
	id uuid primary key default gen_random_uuid(),
	fulfilment_case_id uuid not null references public.fulfilment_cases (id) on delete cascade,
	type text not null check (type in ('deposit', 'final_balance')),
	status text not null default 'not_due' check (status in ('not_due', 'awaiting', 'received', 'not_required')),
	requested_at timestamptz,
	received_at timestamptz,
	received_recorded_by uuid references public.profiles (id) on delete set null,
	note text,
	created_at timestamptz not null default now(),
	updated_at timestamptz not null default now(),
	lock_version bigint not null default 1 check (lock_version > 0),
	constraint payment_milestones_state_evidence check (
		(
			status = 'not_due'
			and requested_at is null
			and received_at is null
			and received_recorded_by is null
		)
		or (
			status = 'awaiting'
			and requested_at is not null
			and received_at is null
			and received_recorded_by is null
		)
		or (
			status = 'received'
			and requested_at is not null
			and received_at is not null
			and received_recorded_by is not null
		)
		or (
			status = 'not_required'
			and received_at is null
			and received_recorded_by is null
		)
	),
	constraint payment_milestones_input_bounds check (
		note is null or char_length(note) <= 2000
	)
);

alter table public.tasks
	add column if not exists fulfilment_case_id uuid references public.fulfilment_cases (id) on delete cascade;

alter table public.activities
	add column if not exists fulfilment_case_id uuid references public.fulfilment_cases (id) on delete cascade;

alter table public.tasks
	drop constraint if exists tasks_type_check,
	add constraint tasks_type_check check (
		type in (
			'review_lead', 'call_client', 'prepare_quote', 'send_quote',
			'follow_up', 'confirm_acceptance', 'custom',
			'plan_fulfilment', 'schedule_installation', 'complete_installation',
			'dispatch_order', 'confirm_delivery', 'prepare_pickup',
			'confirm_collection', 'payment_follow_up'
		)
	);

alter table public.activities
	drop constraint if exists activities_have_target,
	add constraint activities_have_target check (
		lead_id is not null
		or client_id is not null
		or quote_id is not null
		or task_id is not null
		or outbound_message_id is not null
		or fulfilment_case_id is not null
	);

create unique index if not exists fulfilment_cases_accepted_quote_unique
	on public.fulfilment_cases (accepted_quote_id);

create index if not exists fulfilment_cases_status_created_idx
	on public.fulfilment_cases (status, created_at desc, id);

create index if not exists fulfilment_cases_client_idx
	on public.fulfilment_cases (client_id, created_at desc, id);

create unique index if not exists fulfilment_steps_active_type_unique
	on public.fulfilment_steps (fulfilment_case_id, type)
	where status not in ('completed', 'delivered', 'collected', 'cancelled');

create index if not exists fulfilment_steps_case_status_schedule_idx
	on public.fulfilment_steps (fulfilment_case_id, type, status, scheduled_for, id);

create unique index if not exists payment_milestones_case_type_unique
	on public.payment_milestones (fulfilment_case_id, type);

create index if not exists payment_milestones_case_status_idx
	on public.payment_milestones (fulfilment_case_id, status, type, id);

create index if not exists tasks_fulfilment_case_status_due_idx
	on public.tasks (fulfilment_case_id, status, due_at, id)
	where fulfilment_case_id is not null;

create index if not exists activities_fulfilment_case_occurred_idx
	on public.activities (fulfilment_case_id, occurred_at desc, id)
	where fulfilment_case_id is not null;

alter table public.fulfilment_cases enable row level security;
alter table public.fulfilment_steps enable row level security;
alter table public.payment_milestones enable row level security;

revoke all on table public.fulfilment_cases from public, anon, authenticated;
revoke all on table public.fulfilment_steps from public, anon, authenticated;
revoke all on table public.payment_milestones from public, anon, authenticated;
grant select on table public.fulfilment_cases to authenticated;
grant select on table public.fulfilment_steps to authenticated;
grant select on table public.payment_milestones to authenticated;

drop policy if exists fulfilment_cases_select_active on public.fulfilment_cases;
create policy fulfilment_cases_select_active
on public.fulfilment_cases for select to authenticated
using ((select private.has_active_profile()));

drop policy if exists fulfilment_steps_select_active on public.fulfilment_steps;
create policy fulfilment_steps_select_active
on public.fulfilment_steps for select to authenticated
using ((select private.has_active_profile()));

drop policy if exists payment_milestones_select_active on public.payment_milestones;
create policy payment_milestones_select_active
on public.payment_milestones for select to authenticated
using ((select private.has_active_profile()));

create or replace function private.guard_fulfilment_case_mutation()
returns trigger
language plpgsql
set search_path = pg_catalog, public
as $$
begin
	if current_user in ('postgres', 'service_role', 'supabase_admin')
		or (select auth.role()) = 'service_role'
	then
		return coalesce(new, old);
	end if;
	raise exception using errcode = '42501', message = 'FulfilmentCase changes require a trusted action';
end;
$$;

create or replace function private.guard_fulfilment_step_mutation()
returns trigger
language plpgsql
set search_path = pg_catalog, public
as $$
begin
	if current_user in ('postgres', 'service_role', 'supabase_admin')
		or (select auth.role()) = 'service_role'
	then
		return coalesce(new, old);
	end if;
	raise exception using errcode = '42501', message = 'FulfilmentStep changes require a trusted action';
end;
$$;

create or replace function private.guard_payment_milestone_mutation()
returns trigger
language plpgsql
set search_path = pg_catalog, public
as $$
begin
	if current_user in ('postgres', 'service_role', 'supabase_admin')
		or (select auth.role()) = 'service_role'
	then
		return coalesce(new, old);
	end if;
	raise exception using errcode = '42501', message = 'PaymentMilestone changes require a trusted action';
end;
$$;

create or replace function private.guard_fulfilment_activity_insert()
returns trigger
language plpgsql
set search_path = pg_catalog, public
as $$
begin
	if new.fulfilment_case_id is null then
		return new;
	end if;
	if current_user in ('postgres', 'service_role', 'supabase_admin')
		or (select auth.role()) = 'service_role'
	then
		return new;
	end if;
	raise exception using errcode = '42501', message = 'Fulfilment Activity requires a trusted action';
end;
$$;

create or replace function private.validate_task_fulfilment_lineage()
returns trigger
language plpgsql
set search_path = pg_catalog, public
as $$
declare
	v_case public.fulfilment_cases%rowtype;
begin
	if new.fulfilment_case_id is null then
		return new;
	end if;
	select * into v_case
	from public.fulfilment_cases
	where id = new.fulfilment_case_id;
	if not found then
		raise exception using errcode = 'P0002', message = 'FulfilmentCase not found';
	end if;
	if new.lead_id is distinct from v_case.lead_id
		or new.client_id is distinct from v_case.client_id
		or (new.quote_id is not null and new.quote_id is distinct from v_case.accepted_quote_id)
	then
		raise exception using errcode = '23514', message = 'Fulfilment Task lineage does not match its case';
	end if;
	return new;
end;
$$;

create or replace function private.guard_lead_protected_fields()
returns trigger
language plpgsql
set search_path = pg_catalog, public
as $$
begin
	if current_user in ('postgres', 'service_role', 'supabase_admin')
		or (select auth.role()) = 'service_role'
	then
		return new;
	end if;
	if new.pipeline_stage is distinct from old.pipeline_stage
		or new.attention_state is distinct from old.attention_state
		or new.assigned_to is distinct from old.assigned_to
		or new.lost_reason_id is distinct from old.lost_reason_id
		or new.lost_notes is distinct from old.lost_notes
		or new.converted_client_id is distinct from old.converted_client_id
		or new.lock_version is distinct from old.lock_version
		or new.paused_at is distinct from old.paused_at
		or new.pause_reason is distinct from old.pause_reason
		or new.resume_at is distinct from old.resume_at
		or new.phone_normalized is distinct from old.phone_normalized
		or new.qualification_notes is distinct from old.qualification_notes
		or new.qualification_started_at is distinct from old.qualification_started_at
		or new.qualified_at is distinct from old.qualified_at
	then
		raise exception using errcode = '42501', message = 'Lead protected fields require a trusted action';
	end if;
	return new;
end;
$$;

create or replace function private.guard_task_protected_fields()
returns trigger
language plpgsql
set search_path = pg_catalog, public
as $$
begin
	if current_user in ('postgres', 'service_role', 'supabase_admin')
		or (select auth.role()) = 'service_role'
	then
		return new;
	end if;
	if new.status is distinct from old.status
		or new.lock_version is distinct from old.lock_version
		or new.reminder_status is distinct from old.reminder_status
		or new.reminder_claim_id is distinct from old.reminder_claim_id
		or new.reminder_outbound_message_id is distinct from old.reminder_outbound_message_id
		or new.created_by is distinct from old.created_by
		or new.lead_id is distinct from old.lead_id
		or new.client_id is distinct from old.client_id
		or new.quote_id is distinct from old.quote_id
		or new.fulfilment_case_id is distinct from old.fulfilment_case_id
	then
		raise exception using errcode = '42501', message = 'Task protected fields require a trusted action';
	end if;
	return new;
end;
$$;

drop trigger if exists fulfilment_cases_mutation_guard on public.fulfilment_cases;
create trigger fulfilment_cases_mutation_guard
before insert or update or delete on public.fulfilment_cases
for each row execute function private.guard_fulfilment_case_mutation();

drop trigger if exists fulfilment_steps_mutation_guard on public.fulfilment_steps;
create trigger fulfilment_steps_mutation_guard
before insert or update or delete on public.fulfilment_steps
for each row execute function private.guard_fulfilment_step_mutation();

drop trigger if exists payment_milestones_mutation_guard on public.payment_milestones;
create trigger payment_milestones_mutation_guard
before insert or update or delete on public.payment_milestones
for each row execute function private.guard_payment_milestone_mutation();

drop trigger if exists activities_fulfilment_insert_guard on public.activities;
create trigger activities_fulfilment_insert_guard
before insert on public.activities
for each row execute function private.guard_fulfilment_activity_insert();

drop trigger if exists tasks_fulfilment_lineage on public.tasks;
create trigger tasks_fulfilment_lineage
before insert or update on public.tasks
for each row execute function private.validate_task_fulfilment_lineage();

drop trigger if exists fulfilment_cases_updated_at on public.fulfilment_cases;
create trigger fulfilment_cases_updated_at
before update on public.fulfilment_cases
for each row execute function private.set_updated_at();

drop trigger if exists fulfilment_steps_updated_at on public.fulfilment_steps;
create trigger fulfilment_steps_updated_at
before update on public.fulfilment_steps
for each row execute function private.set_updated_at();

drop trigger if exists payment_milestones_updated_at on public.payment_milestones;
create trigger payment_milestones_updated_at
before update on public.payment_milestones
for each row execute function private.set_updated_at();

drop trigger if exists fulfilment_cases_lock_version on public.fulfilment_cases;
create trigger fulfilment_cases_lock_version
before update on public.fulfilment_cases
for each row execute function private.enforce_lock_version();

drop trigger if exists fulfilment_steps_lock_version on public.fulfilment_steps;
create trigger fulfilment_steps_lock_version
before update on public.fulfilment_steps
for each row execute function private.enforce_lock_version();

drop trigger if exists payment_milestones_lock_version on public.payment_milestones;
create trigger payment_milestones_lock_version
before update on public.payment_milestones
for each row execute function private.enforce_lock_version();

create or replace function public.start_lead_qualification(
	p_lead_id uuid,
	p_lock_version bigint,
	p_qualification_notes text default null
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
	v_actor uuid := (select auth.uid());
	v_lead public.leads%rowtype;
	v_new_lock bigint;
	v_notes text := nullif(trim(coalesce(p_qualification_notes, '')), '');
begin
	if v_actor is null or not (select private.has_any_role(array['owner', 'admin', 'sales']::text[])) then
		raise exception using errcode = '42501', message = 'CRM role required';
	end if;
	select * into v_lead from public.leads where id = p_lead_id for update;
	if not found then raise exception using errcode = 'P0002', message = 'Lead not found'; end if;
	if v_lead.pipeline_stage = 'QUALIFICATION' then
		return jsonb_build_object(
			'lead_id', v_lead.id,
			'pipeline_stage', v_lead.pipeline_stage,
			'lock_version', v_lead.lock_version,
			'idempotent', true
		);
	end if;
	if v_lead.pipeline_stage <> 'NEW' then
		raise exception using errcode = '22023', message = 'Only NEW Leads can start qualification';
	end if;
	if p_lock_version is distinct from v_lead.lock_version then
		raise exception using errcode = '40001', message = 'Stale lead lock_version';
	end if;
	update public.leads
	set pipeline_stage = 'QUALIFICATION',
		qualification_started_at = coalesce(qualification_started_at, now()),
		qualification_notes = coalesce(v_notes, qualification_notes),
		attention_state = 'none',
		attention_reason = null,
		attention_resume_at = null,
		last_activity_at = now(),
		lock_version = lock_version + 1
	where id = p_lead_id and lock_version = p_lock_version
	returning lock_version into v_new_lock;
	if v_new_lock is null then raise exception using errcode = '40001', message = 'Stale lead lock_version'; end if;
	insert into public.activities (lead_id, actor_id, event_type, metadata, summary)
	values (
		p_lead_id,
		v_actor,
		'lead_qualification_started',
		jsonb_build_object('from_stage', 'NEW', 'to_stage', 'QUALIFICATION', 'has_notes', v_notes is not null),
		'Lead qualification started'
	);
	return jsonb_build_object(
		'lead_id', p_lead_id,
		'pipeline_stage', 'QUALIFICATION',
		'lock_version', v_new_lock,
		'idempotent', false
	);
end;
$$;

create or replace function public.ready_lead_for_quote(
	p_lead_id uuid,
	p_lock_version bigint,
	p_qualification_notes text default null
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
	v_actor uuid := (select auth.uid());
	v_lead public.leads%rowtype;
	v_new_lock bigint;
	v_notes text := coalesce(nullif(trim(coalesce(p_qualification_notes, '')), ''), null);
	v_has_contact boolean;
	v_has_enquiry boolean;
begin
	if v_actor is null or not (select private.has_any_role(array['owner', 'admin', 'sales']::text[])) then
		raise exception using errcode = '42501', message = 'CRM role required';
	end if;
	select * into v_lead from public.leads where id = p_lead_id for update;
	if not found then raise exception using errcode = 'P0002', message = 'Lead not found'; end if;
	if v_lead.pipeline_stage = 'PROPOSAL' and v_lead.qualified_at is not null then
		return jsonb_build_object(
			'lead_id', v_lead.id,
			'pipeline_stage', v_lead.pipeline_stage,
			'lock_version', v_lead.lock_version,
			'idempotent', true
		);
	end if;
	if v_lead.pipeline_stage <> 'QUALIFICATION' then
		raise exception using errcode = '22023', message = 'Only Leads in qualification can be made ready for quote';
	end if;
	if p_lock_version is distinct from v_lead.lock_version then
		raise exception using errcode = '40001', message = 'Stale lead lock_version';
	end if;
	v_has_contact := length(trim(coalesce(v_lead.email, ''))) > 0
		or length(trim(coalesce(v_lead.phone, ''))) > 0;
	v_has_enquiry := length(trim(coalesce(v_lead.message, ''))) > 0
		or length(trim(coalesce(v_notes, v_lead.qualification_notes, ''))) > 0;
	if not v_has_contact then
		raise exception using errcode = '23514', message = 'Ready for Quote requires an email or phone';
	end if;
	if not v_has_enquiry then
		raise exception using errcode = '23514', message = 'Ready for Quote requires enquiry information';
	end if;
	update public.leads
	set pipeline_stage = 'PROPOSAL',
		qualification_notes = coalesce(v_notes, qualification_notes),
		qualification_started_at = coalesce(qualification_started_at, now()),
		qualified_at = coalesce(qualified_at, now()),
		attention_state = 'waiting_on_us',
		attention_reason = 'Quote preparation required',
		attention_resume_at = null,
		last_activity_at = now(),
		lock_version = lock_version + 1
	where id = p_lead_id and lock_version = p_lock_version
	returning lock_version into v_new_lock;
	if v_new_lock is null then raise exception using errcode = '40001', message = 'Stale lead lock_version'; end if;
	insert into public.activities (lead_id, actor_id, event_type, metadata, summary)
	values (
		p_lead_id,
		v_actor,
		'lead_ready_for_quote',
		jsonb_build_object('from_stage', 'QUALIFICATION', 'to_stage', 'PROPOSAL'),
		'Lead ready for quote preparation'
	);
	return jsonb_build_object(
		'lead_id', p_lead_id,
		'pipeline_stage', 'PROPOSAL',
		'lock_version', v_new_lock,
		'idempotent', false
	);
end;
$$;

-- Preserve the v1.3.2 transition endpoint used by existing screens and tests,
-- while making its two qualification transitions record their timestamps.
create or replace function public.transition_lead(
	p_lead_id uuid,
	p_to_stage text,
	p_lock_version bigint,
	p_lost_reason_id uuid default null,
	p_lost_notes text default null
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
	v_lead public.leads%rowtype;
	v_reason_code text;
	v_new_lock bigint;
	v_closed_task_count integer := 0;
	v_closed_task_ids uuid[] := '{}'::uuid[];
begin
	if not (select private.has_any_role(array['owner', 'admin', 'sales']::text[])) then
		raise exception using errcode = '42501', message = 'CRM role required';
	end if;
	select * into v_lead from public.leads where id = p_lead_id for update;
	if not found then raise exception using errcode = 'P0002', message = 'Lead not found'; end if;
	if p_lock_version is distinct from v_lead.lock_version then
		raise exception using errcode = '40001', message = 'Stale lead lock_version';
	end if;
	if not (
		(v_lead.pipeline_stage = 'NEW' and p_to_stage in ('QUALIFICATION', 'LOST'))
		or (v_lead.pipeline_stage = 'QUALIFICATION' and p_to_stage in ('PROPOSAL', 'LOST'))
		or (v_lead.pipeline_stage = 'PROPOSAL' and p_to_stage in ('DECISION', 'LOST'))
		or (v_lead.pipeline_stage = 'DECISION' and p_to_stage in ('PROPOSAL', 'LOST'))
	) then
		raise exception using errcode = '22023', message = 'No legal lead pipeline transition';
	end if;
	if p_to_stage = 'LOST' then
		select code into v_reason_code from public.lost_reasons where id = p_lost_reason_id and active;
		if v_reason_code is null then raise exception using errcode = '23514', message = 'LOST leads require an active lost reason'; end if;
		if v_reason_code = 'other' and length(trim(coalesce(p_lost_notes, ''))) = 0 then raise exception using errcode = '23514', message = 'The other lost reason requires lost_notes'; end if;
	end if;
	update public.leads
	set pipeline_stage = p_to_stage,
		qualification_started_at = case when p_to_stage = 'QUALIFICATION' then coalesce(qualification_started_at, now()) else qualification_started_at end,
		qualified_at = case when p_to_stage = 'PROPOSAL' and v_lead.pipeline_stage = 'QUALIFICATION' then coalesce(qualified_at, now()) else qualified_at end,
		attention_state = 'none',
		lost_reason_id = case when p_to_stage = 'LOST' then p_lost_reason_id else null end,
		lost_notes = case when p_to_stage = 'LOST' then nullif(trim(p_lost_notes), '') else null end,
		last_activity_at = now(),
		lock_version = lock_version + 1
	where id = p_lead_id and lock_version = p_lock_version
	returning lock_version into v_new_lock;
	if v_new_lock is null then raise exception using errcode = '40001', message = 'Stale lead lock_version'; end if;
	if p_to_stage = 'LOST' then
		with closed_tasks as (
			update public.tasks
			set status = 'cancelled', cancelled_at = now(), lock_version = lock_version + 1
			where lead_id = p_lead_id and status = 'open'
			returning id
		)
		select count(*)::integer, coalesce(array_agg(id), '{}'::uuid[]) into v_closed_task_count, v_closed_task_ids from closed_tasks;
	end if;
	insert into public.activities (lead_id, actor_id, event_type, metadata, summary)
	values (
		p_lead_id,
		auth.uid(),
		case when p_to_stage = 'LOST' then 'lead_lost' else 'pipeline_changed' end,
		jsonb_build_object(
			'from_stage', v_lead.pipeline_stage,
			'to_stage', p_to_stage,
			'closed_task_count', v_closed_task_count,
			'closed_task_ids', to_jsonb(v_closed_task_ids)
		),
		case when p_to_stage = 'LOST' then 'Lead marked lost' else format('Lead moved to %s', p_to_stage) end
	);
	return jsonb_build_object('lead_id', p_lead_id, 'pipeline_stage', p_to_stage, 'lock_version', v_new_lock, 'closed_task_count', v_closed_task_count);
end;
$$;

create or replace function public.reopen_lead(
	p_lead_id uuid,
	p_lock_version bigint,
	p_reason text
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
	v_lead public.leads%rowtype;
	v_reason text := nullif(trim(coalesce(p_reason, '')), '');
	v_new_lock bigint;
begin
	if not (select private.has_any_role(array['owner', 'admin']::text[])) then
		raise exception using errcode = '42501', message = 'Owner or admin role required';
	end if;
	if v_reason is null then raise exception using errcode = '22023', message = 'A reopen reason is required'; end if;
	select * into v_lead from public.leads where id = p_lead_id for update;
	if not found then raise exception using errcode = 'P0002', message = 'Lead not found'; end if;
	if v_lead.pipeline_stage <> 'LOST' then raise exception using errcode = '22023', message = 'Only lost leads can be reopened'; end if;
	if p_lock_version is distinct from v_lead.lock_version then raise exception using errcode = '40001', message = 'Stale lead lock_version'; end if;
	update public.leads
	set pipeline_stage = 'QUALIFICATION',
		qualification_started_at = coalesce(qualification_started_at, now()),
		qualified_at = null,
		attention_state = 'none',
		attention_reason = null,
		attention_resume_at = null,
		lost_reason_id = null,
		lost_notes = null,
		last_activity_at = now(),
		lock_version = lock_version + 1
	where id = p_lead_id and lock_version = p_lock_version
	returning lock_version into v_new_lock;
	if v_new_lock is null then raise exception using errcode = '40001', message = 'Stale lead lock_version'; end if;
	insert into public.activities (lead_id, actor_id, event_type, metadata, summary)
	values (p_lead_id, auth.uid(), 'lead_reopened', jsonb_build_object('from_stage', 'LOST', 'to_stage', 'QUALIFICATION', 'reason', v_reason), 'Lead reopened for qualification');
	return jsonb_build_object('lead_id', p_lead_id, 'pipeline_stage', 'QUALIFICATION', 'lock_version', v_new_lock);
end;
$$;

create or replace function private.create_task_impl(
	p_fulfilment_case_id uuid,
	p_lead_id uuid,
	p_client_id uuid,
	p_quote_id uuid,
	p_type text,
	p_title text,
	p_description text,
	p_assigned_to uuid,
	p_due_at timestamptz,
	p_automation_key text
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
	v_actor uuid := (select auth.uid());
	v_task public.tasks%rowtype;
	v_existing public.tasks%rowtype;
	v_quote public.quotes%rowtype;
	v_lead public.leads%rowtype;
	v_case public.fulfilment_cases%rowtype;
	v_lead_id uuid := p_lead_id;
	v_client_id uuid := p_client_id;
	v_parent_count integer;
begin
	if v_actor is null or not (select private.has_any_role(array['owner', 'admin', 'sales']::text[])) then
		raise exception using errcode = '42501', message = 'CRM role required';
	end if;
	if p_automation_key is not null then
		raise exception using errcode = '42501', message = 'Automation keys require a trusted action';
	end if;
	if length(trim(coalesce(p_title, ''))) = 0 then
		raise exception using errcode = '22023', message = 'Task title is required';
	end if;

	if p_fulfilment_case_id is not null then
		if p_type not in ('plan_fulfilment', 'schedule_installation', 'complete_installation', 'dispatch_order', 'confirm_delivery', 'prepare_pickup', 'confirm_collection', 'payment_follow_up') then
			raise exception using errcode = '22023', message = 'Invalid Fulfilment Task type';
		end if;
		select * into v_case from public.fulfilment_cases where id = p_fulfilment_case_id for update;
		if not found then raise exception using errcode = 'P0002', message = 'FulfilmentCase not found'; end if;
		if v_case.status <> 'open' then raise exception using errcode = '55000', message = 'Closed FulfilmentCases cannot receive Tasks'; end if;
		v_lead_id := v_case.lead_id;
		v_client_id := v_case.client_id;
		if p_lead_id is not null and p_lead_id is distinct from v_lead_id then raise exception using errcode = '23514', message = 'Fulfilment Task Lead does not match its case'; end if;
		if p_client_id is not null and p_client_id is distinct from v_client_id then raise exception using errcode = '23514', message = 'Fulfilment Task Client does not match its case'; end if;
		if p_quote_id is not null and p_quote_id is distinct from v_case.accepted_quote_id then raise exception using errcode = '23514', message = 'Fulfilment Task Quote does not match its case'; end if;
		if p_type = 'payment_follow_up' then
			select * into v_existing
			from public.tasks
			where fulfilment_case_id = p_fulfilment_case_id
				and type = 'payment_follow_up'
				and status = 'open'
			order by created_at, id
			limit 1
			for update;
			if found then
				return jsonb_build_object('task_id', v_existing.id, 'lock_version', v_existing.lock_version, 'idempotent', true);
			end if;
		end if;
	else
		if p_quote_id is not null then
			select * into v_quote from public.quotes where id = p_quote_id for share;
			if not found then raise exception using errcode = 'P0002', message = 'Quote not found'; end if;
			select * into v_lead from public.leads where id = v_quote.lead_id for share;
			v_lead_id := v_quote.lead_id;
			v_client_id := coalesce(v_quote.client_id, v_lead.converted_client_id);
			if p_lead_id is not null and p_lead_id <> v_lead_id then raise exception using errcode = '23514', message = 'Task Lead does not match Quote'; end if;
			if p_client_id is not null and p_client_id is distinct from v_client_id then raise exception using errcode = '23514', message = 'Task Client does not match Quote'; end if;
		else
			if p_type not in ('review_lead', 'call_client', 'prepare_quote', 'send_quote', 'follow_up', 'confirm_acceptance', 'custom') then
				raise exception using errcode = '22023', message = 'Invalid Task type';
			end if;
			v_parent_count := (p_lead_id is not null)::integer + (p_client_id is not null)::integer;
			if v_parent_count <> 1 then raise exception using errcode = '23514', message = 'A Task without a Quote requires exactly one Lead or Client'; end if;
			if p_lead_id is not null and not exists (select 1 from public.leads where id = p_lead_id) then raise exception using errcode = 'P0002', message = 'Lead not found'; end if;
			if p_client_id is not null and not exists (select 1 from public.clients where id = p_client_id) then raise exception using errcode = 'P0002', message = 'Client not found'; end if;
		end if;
	end if;

	if p_assigned_to is not null and not exists (
		select 1 from public.profiles where id = p_assigned_to and status = 'active' and role in ('owner', 'admin', 'sales')
	) then
		raise exception using errcode = '22023', message = 'Task assignee must be an active CRM user';
	end if;

	insert into public.tasks (
		lead_id, client_id, quote_id, fulfilment_case_id, type, title, description,
		assigned_to, due_at, created_by
	)
	values (
		v_lead_id,
		v_client_id,
		p_quote_id,
		p_fulfilment_case_id,
		p_type,
		trim(p_title),
		nullif(trim(coalesce(p_description, '')), ''),
		p_assigned_to,
		p_due_at,
		v_actor
	)
	returning * into v_task;
	return jsonb_build_object('task_id', v_task.id, 'lock_version', v_task.lock_version, 'idempotent', false);
exception when unique_violation then
	if p_fulfilment_case_id is not null and p_type = 'payment_follow_up' then
		select * into v_existing
		from public.tasks
		where fulfilment_case_id = p_fulfilment_case_id and type = 'payment_follow_up' and status = 'open'
		order by created_at, id
		limit 1;
		if found then return jsonb_build_object('task_id', v_existing.id, 'lock_version', v_existing.lock_version, 'idempotent', true); end if;
	end if;
	raise;
end;
$$;

create or replace function public.create_task(
	p_lead_id uuid default null,
	p_client_id uuid default null,
	p_quote_id uuid default null,
	p_type text default 'custom',
	p_title text default null,
	p_description text default null,
	p_assigned_to uuid default null,
	p_due_at timestamptz default null,
	p_automation_key text default null
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
begin
	return private.create_task_impl(
		null,
		p_lead_id,
		p_client_id,
		p_quote_id,
		p_type,
		p_title,
		p_description,
		p_assigned_to,
		p_due_at,
		p_automation_key
	);
end;
$$;

create function public.create_task(
	p_fulfilment_case_id uuid,
	p_lead_id uuid default null,
	p_client_id uuid default null,
	p_quote_id uuid default null,
	p_type text default 'plan_fulfilment',
	p_title text default null,
	p_description text default null,
	p_assigned_to uuid default null,
	p_due_at timestamptz default null,
	p_automation_key text default null
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
begin
	return private.create_task_impl(
		p_fulfilment_case_id,
		p_lead_id,
		p_client_id,
		p_quote_id,
		p_type,
		p_title,
		p_description,
		p_assigned_to,
		p_due_at,
		p_automation_key
	);
end;
$$;

create or replace function private.record_task_activity()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
	v_event_type text;
	v_summary text;
	v_metadata jsonb;
begin
	if tg_op = 'INSERT' then
		v_event_type := case when new.fulfilment_case_id is not null and new.type = 'payment_follow_up' then 'payment_follow_up_created' else 'task_created' end;
		v_summary := case
			when new.type = 'follow_up' then 'Follow-up task created'
			when new.type = 'payment_follow_up' then 'Payment follow-up task created'
			else format('Task created: %s', new.title)
		end;
		v_metadata := jsonb_build_object('task_type', new.type, 'automation_key', new.automation_key, 'due_at', new.due_at);
	elsif old.status = 'open' and new.status = 'completed' then
		v_event_type := 'task_completed';
		v_summary := format('Task completed: %s', new.title);
		v_metadata := jsonb_build_object('task_type', new.type, 'lock_version', new.lock_version);
	elsif old.status = 'open' and new.status = 'cancelled' then
		v_event_type := 'task_cancelled';
		v_summary := format('Task cancelled: %s', new.title);
		v_metadata := jsonb_build_object('task_type', new.type, 'lock_version', new.lock_version);
	elsif old.status = 'open' and new.status = 'open' and new.due_at is distinct from old.due_at then
		v_event_type := 'task_rescheduled';
		v_summary := format('Task rescheduled: %s', new.title);
		v_metadata := jsonb_build_object('task_type', new.type, 'from_due_at', old.due_at, 'to_due_at', new.due_at, 'lock_version', new.lock_version);
	else
		return new;
	end if;
	insert into public.activities (
		lead_id, client_id, quote_id, task_id, fulfilment_case_id, actor_id,
		event_type, metadata, summary
	)
	values (
		new.lead_id, new.client_id, new.quote_id, new.id, new.fulfilment_case_id,
		auth.uid(), v_event_type, v_metadata, v_summary
	);
	return new;
end;
$$;

drop index if exists public.tasks_fulfilment_payment_follow_up_unique;
create unique index tasks_fulfilment_payment_follow_up_unique
on public.tasks (fulfilment_case_id)
where fulfilment_case_id is not null and type = 'payment_follow_up' and status = 'open';

create or replace function private.create_fulfilment_case_for_accepted_quote(
	p_quote_id uuid,
	p_actor uuid default null
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
	v_actor uuid := coalesce(p_actor, (select auth.uid()));
	v_quote public.quotes%rowtype;
	v_lead public.leads%rowtype;
	v_case public.fulfilment_cases%rowtype;
begin
	-- Quote is the input authority, so every handoff locks Quote before Lead.
	select * into v_quote from public.quotes where id = p_quote_id for update;
	if not found then raise exception using errcode = 'P0002', message = 'Quote not found'; end if;
	select * into v_lead from public.leads where id = v_quote.lead_id for update;
	if not found then raise exception using errcode = 'P0002', message = 'Lead not found'; end if;
	select * into v_case from public.fulfilment_cases where accepted_quote_id = p_quote_id for update;
	if found then
		return jsonb_build_object(
			'fulfilment_case_id', v_case.id,
			'fulfilment_number', v_case.fulfilment_number,
			'client_id', v_case.client_id,
			'lead_id', v_case.lead_id,
			'accepted_quote_id', v_case.accepted_quote_id,
			'lock_version', v_case.lock_version,
			'idempotent', true
		);
	end if;
	if v_quote.status <> 'accepted' or v_quote.accepted_at is null or length(trim(coalesce(v_quote.acceptance_source, ''))) = 0 then
		raise exception using errcode = '22023', message = 'Only an accepted Quote can create a FulfilmentCase';
	end if;
	if v_lead.pipeline_stage <> 'WON' or v_lead.converted_client_id is null then
		raise exception using errcode = '22023', message = 'Accepted Quote requires a converted WON Lead';
	end if;
	if v_quote.client_id is distinct from v_lead.converted_client_id then
		raise exception using errcode = '23514', message = 'Accepted Quote Client does not match its Lead';
	end if;
	insert into public.fulfilment_cases (client_id, lead_id, accepted_quote_id)
	values (v_lead.converted_client_id, v_lead.id, v_quote.id)
	returning * into v_case;
	insert into public.payment_milestones (fulfilment_case_id, type)
	values (v_case.id, 'deposit'), (v_case.id, 'final_balance');
	insert into public.activities (
		lead_id, client_id, quote_id, fulfilment_case_id, actor_id,
		event_type, metadata, summary
	)
	values (
		v_lead.id,
		v_case.client_id,
		v_quote.id,
		v_case.id,
		v_actor,
		'fulfilment_created',
		jsonb_build_object('fulfilment_number', v_case.fulfilment_number, 'accepted_quote_id', v_quote.id),
		'Fulfilment case created from accepted Quote'
	);
	return jsonb_build_object(
		'fulfilment_case_id', v_case.id,
		'fulfilment_number', v_case.fulfilment_number,
		'client_id', v_case.client_id,
		'lead_id', v_case.lead_id,
		'accepted_quote_id', v_case.accepted_quote_id,
		'lock_version', v_case.lock_version,
		'idempotent', false
	);
exception when unique_violation then
	select * into v_case from public.fulfilment_cases where accepted_quote_id = p_quote_id;
	if found then
		return jsonb_build_object(
			'fulfilment_case_id', v_case.id,
			'fulfilment_number', v_case.fulfilment_number,
			'client_id', v_case.client_id,
			'lead_id', v_case.lead_id,
			'accepted_quote_id', v_case.accepted_quote_id,
			'lock_version', v_case.lock_version,
			'idempotent', true
		);
	end if;
	raise;
end;
$$;

create or replace function public.create_fulfilment_case_for_accepted_quote(p_quote_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
begin
	if current_user not in ('postgres', 'service_role', 'supabase_admin')
		and (select auth.role()) <> 'service_role'
	then
		raise exception using errcode = '42501', message = 'Internal fulfilment handoff only';
	end if;
	return private.create_fulfilment_case_for_accepted_quote(p_quote_id, (select auth.uid()));
end;
$$;

create or replace function public.create_fulfilment_step(
	p_fulfilment_case_id uuid,
	p_type text,
	p_lock_version bigint,
	p_notes text default null,
	p_tracking_reference text default null
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
	v_actor uuid := (select auth.uid());
	v_case public.fulfilment_cases%rowtype;
	v_step public.fulfilment_steps%rowtype;
	v_status text;
	v_case_lock bigint;
begin
	if v_actor is null or not (select private.has_any_role(array['owner', 'admin', 'sales']::text[])) then
		raise exception using errcode = '42501', message = 'CRM role required';
	end if;
	if p_type not in ('installation', 'courier', 'pickup') then raise exception using errcode = '22023', message = 'Invalid FulfilmentStep type'; end if;
	select * into v_case from public.fulfilment_cases where id = p_fulfilment_case_id for update;
	if not found then raise exception using errcode = 'P0002', message = 'FulfilmentCase not found'; end if;
	if v_case.status <> 'open' then raise exception using errcode = '55000', message = 'Closed FulfilmentCases cannot receive steps'; end if;
	perform 1
	from public.fulfilment_steps
	where fulfilment_case_id = p_fulfilment_case_id
		and type = p_type
		and status not in ('completed', 'delivered', 'collected', 'cancelled')
	limit 1;
	if found then
		raise exception using errcode = '23505', message = 'An active FulfilmentStep of this type already exists';
	end if;
	if p_lock_version is distinct from v_case.lock_version then raise exception using errcode = '40001', message = 'Stale FulfilmentCase lock_version'; end if;
	v_status := case p_type when 'installation' then 'awaiting_schedule' when 'courier' then 'awaiting_dispatch' else 'preparing' end;
	insert into public.fulfilment_steps (fulfilment_case_id, type, status, notes, tracking_reference)
	values (
		p_fulfilment_case_id,
		p_type,
		v_status,
		nullif(trim(coalesce(p_notes, '')), ''),
		nullif(trim(coalesce(p_tracking_reference, '')), '')
	)
	returning * into v_step;
	update public.fulfilment_cases
	set lock_version = lock_version + 1
	where id = p_fulfilment_case_id and lock_version = p_lock_version
	returning lock_version into v_case_lock;
	if v_case_lock is null then raise exception using errcode = '40001', message = 'FulfilmentCase changed during step creation'; end if;
	insert into public.activities (lead_id, client_id, quote_id, fulfilment_case_id, actor_id, event_type, metadata, summary)
	values (
		v_case.lead_id,
		v_case.client_id,
		v_case.accepted_quote_id,
		v_case.id,
		v_actor,
		'fulfilment_step_created',
		jsonb_build_object('step_id', v_step.id, 'type', v_step.type, 'status', v_step.status),
		format('%s step created', initcap(v_step.type))
	);
	return jsonb_build_object('step_id', v_step.id, 'status', v_step.status, 'lock_version', v_step.lock_version, 'fulfilment_case_lock_version', v_case_lock, 'idempotent', false);
end;
$$;

create or replace function public.schedule_fulfilment_step(
	p_step_id uuid,
	p_lock_version bigint,
	p_scheduled_for timestamptz
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
	v_actor uuid := (select auth.uid());
	v_case public.fulfilment_cases%rowtype;
	v_step public.fulfilment_steps%rowtype;
	v_case_id uuid;
	v_case_lock bigint;
begin
	if v_actor is null or not (select private.has_any_role(array['owner', 'admin', 'sales']::text[])) then raise exception using errcode = '42501', message = 'CRM role required'; end if;
	if p_scheduled_for is null then raise exception using errcode = '22023', message = 'A scheduled time is required'; end if;
	select fulfilment_case_id into v_case_id from public.fulfilment_steps where id = p_step_id;
	if not found then raise exception using errcode = 'P0002', message = 'FulfilmentStep not found'; end if;
	select * into v_case from public.fulfilment_cases where id = v_case_id for update;
	select * into v_step from public.fulfilment_steps where id = p_step_id for update;
	if v_case.status <> 'open' then raise exception using errcode = '55000', message = 'Closed FulfilmentCases are read-only'; end if;
	if v_step.type <> 'installation' or v_step.status <> 'awaiting_schedule' then raise exception using errcode = '22023', message = 'Only awaiting installation steps can be scheduled'; end if;
	if v_step.lock_version is distinct from p_lock_version then raise exception using errcode = '40001', message = 'Stale FulfilmentStep lock_version'; end if;
	update public.fulfilment_steps
	set status = 'scheduled', scheduled_for = p_scheduled_for, lock_version = lock_version + 1
	where id = p_step_id and lock_version = p_lock_version
	returning * into v_step;
	update public.fulfilment_cases
	set lock_version = lock_version + 1
	where id = v_case.id
	returning lock_version into v_case_lock;
	insert into public.activities (lead_id, client_id, quote_id, fulfilment_case_id, actor_id, event_type, metadata, summary)
	values (v_case.lead_id, v_case.client_id, v_case.accepted_quote_id, v_case.id, v_actor, 'fulfilment_step_scheduled', jsonb_build_object('step_id', v_step.id, 'scheduled_for', v_step.scheduled_for), 'Installation scheduled');
	return jsonb_build_object('step_id', v_step.id, 'status', v_step.status, 'scheduled_for', v_step.scheduled_for, 'lock_version', v_step.lock_version, 'fulfilment_case_lock_version', v_case_lock);
end;
$$;

create or replace function public.reschedule_fulfilment_step(
	p_step_id uuid,
	p_lock_version bigint,
	p_scheduled_for timestamptz
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
	v_actor uuid := (select auth.uid());
	v_case public.fulfilment_cases%rowtype;
	v_step public.fulfilment_steps%rowtype;
	v_old_scheduled_for timestamptz;
	v_case_id uuid;
	v_case_lock bigint;
begin
	if v_actor is null or not (select private.has_any_role(array['owner', 'admin', 'sales']::text[])) then raise exception using errcode = '42501', message = 'CRM role required'; end if;
	if p_scheduled_for is null then raise exception using errcode = '22023', message = 'A scheduled time is required'; end if;
	select fulfilment_case_id into v_case_id from public.fulfilment_steps where id = p_step_id;
	if not found then raise exception using errcode = 'P0002', message = 'FulfilmentStep not found'; end if;
	select * into v_case from public.fulfilment_cases where id = v_case_id for update;
	select * into v_step from public.fulfilment_steps where id = p_step_id for update;
	if v_case.status <> 'open' then raise exception using errcode = '55000', message = 'Closed FulfilmentCases are read-only'; end if;
	if v_step.type <> 'installation' or v_step.status <> 'scheduled' then raise exception using errcode = '22023', message = 'Only scheduled installation steps can be rescheduled'; end if;
	if v_step.lock_version is distinct from p_lock_version then raise exception using errcode = '40001', message = 'Stale FulfilmentStep lock_version'; end if;
	v_old_scheduled_for := v_step.scheduled_for;
	update public.fulfilment_steps
	set scheduled_for = p_scheduled_for, lock_version = lock_version + 1
	where id = p_step_id and lock_version = p_lock_version
	returning * into v_step;
	update public.fulfilment_cases set lock_version = lock_version + 1 where id = v_case.id returning lock_version into v_case_lock;
	insert into public.activities (lead_id, client_id, quote_id, fulfilment_case_id, actor_id, event_type, metadata, summary)
	values (v_case.lead_id, v_case.client_id, v_case.accepted_quote_id, v_case.id, v_actor, 'fulfilment_step_rescheduled', jsonb_build_object('step_id', v_step.id, 'from_scheduled_for', v_old_scheduled_for, 'to_scheduled_for', v_step.scheduled_for), 'Installation rescheduled');
	return jsonb_build_object('step_id', v_step.id, 'status', v_step.status, 'scheduled_for', v_step.scheduled_for, 'lock_version', v_step.lock_version, 'fulfilment_case_lock_version', v_case_lock);
end;
$$;

create or replace function public.complete_fulfilment_step(
	p_step_id uuid,
	p_lock_version bigint
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
	v_actor uuid := (select auth.uid());
	v_case public.fulfilment_cases%rowtype;
	v_step public.fulfilment_steps%rowtype;
	v_case_id uuid;
	v_status text;
	v_case_lock bigint;
begin
	if v_actor is null or not (select private.has_any_role(array['owner', 'admin', 'sales']::text[])) then raise exception using errcode = '42501', message = 'CRM role required'; end if;
	select fulfilment_case_id into v_case_id from public.fulfilment_steps where id = p_step_id;
	if not found then raise exception using errcode = 'P0002', message = 'FulfilmentStep not found'; end if;
	select * into v_case from public.fulfilment_cases where id = v_case_id for update;
	select * into v_step from public.fulfilment_steps where id = p_step_id for update;
	if v_case.status <> 'open' then raise exception using errcode = '55000', message = 'Closed FulfilmentCases are read-only'; end if;
	if not ((v_step.type = 'installation' and v_step.status = 'scheduled') or (v_step.type = 'courier' and v_step.status = 'dispatched') or (v_step.type = 'pickup' and v_step.status = 'ready_for_collection')) then
		raise exception using errcode = '22023', message = 'FulfilmentStep is not ready for completion';
	end if;
	if v_step.lock_version is distinct from p_lock_version then raise exception using errcode = '40001', message = 'Stale FulfilmentStep lock_version'; end if;
	v_status := case v_step.type when 'installation' then 'completed' when 'courier' then 'delivered' else 'collected' end;
	update public.fulfilment_steps
	set status = v_status, completed_at = now(), lock_version = lock_version + 1
	where id = p_step_id and lock_version = p_lock_version
	returning * into v_step;
	update public.fulfilment_cases set lock_version = lock_version + 1 where id = v_case.id returning lock_version into v_case_lock;
	insert into public.activities (lead_id, client_id, quote_id, fulfilment_case_id, actor_id, event_type, metadata, summary)
	values (v_case.lead_id, v_case.client_id, v_case.accepted_quote_id, v_case.id, v_actor, 'fulfilment_step_completed', jsonb_build_object('step_id', v_step.id, 'type', v_step.type, 'status', v_step.status), format('%s step completed', initcap(v_step.type)));
	return jsonb_build_object('step_id', v_step.id, 'status', v_step.status, 'completed_at', v_step.completed_at, 'lock_version', v_step.lock_version, 'fulfilment_case_lock_version', v_case_lock);
end;
$$;

create or replace function public.cancel_fulfilment_step(
	p_step_id uuid,
	p_lock_version bigint,
	p_reason text
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
	v_actor uuid := (select auth.uid());
	v_case public.fulfilment_cases%rowtype;
	v_step public.fulfilment_steps%rowtype;
	v_reason text := nullif(trim(coalesce(p_reason, '')), '');
	v_case_id uuid;
	v_case_lock bigint;
begin
	if v_actor is null or not (select private.has_any_role(array['owner', 'admin', 'sales']::text[])) then raise exception using errcode = '42501', message = 'CRM role required'; end if;
	if v_reason is null then raise exception using errcode = '22023', message = 'Step cancellation reason is required'; end if;
	select fulfilment_case_id into v_case_id from public.fulfilment_steps where id = p_step_id;
	if not found then raise exception using errcode = 'P0002', message = 'FulfilmentStep not found'; end if;
	select * into v_case from public.fulfilment_cases where id = v_case_id for update;
	select * into v_step from public.fulfilment_steps where id = p_step_id for update;
	if v_case.status <> 'open' then raise exception using errcode = '55000', message = 'Closed FulfilmentCases are read-only'; end if;
	if v_step.status not in ('awaiting_schedule', 'scheduled', 'awaiting_dispatch', 'dispatched', 'preparing', 'ready_for_collection') then raise exception using errcode = '22023', message = 'Only active FulfilmentSteps can be cancelled'; end if;
	if v_step.lock_version is distinct from p_lock_version then raise exception using errcode = '40001', message = 'Stale FulfilmentStep lock_version'; end if;
	update public.fulfilment_steps
	set status = 'cancelled', cancelled_at = now(), cancel_reason = v_reason, lock_version = lock_version + 1
	where id = p_step_id and lock_version = p_lock_version
	returning * into v_step;
	update public.fulfilment_cases set lock_version = lock_version + 1 where id = v_case.id returning lock_version into v_case_lock;
	insert into public.activities (lead_id, client_id, quote_id, fulfilment_case_id, actor_id, event_type, metadata, summary)
	values (v_case.lead_id, v_case.client_id, v_case.accepted_quote_id, v_case.id, v_actor, 'fulfilment_step_cancelled', jsonb_build_object('step_id', v_step.id, 'reason', v_reason), format('%s step cancelled', initcap(v_step.type)));
	return jsonb_build_object('step_id', v_step.id, 'status', v_step.status, 'lock_version', v_step.lock_version, 'fulfilment_case_lock_version', v_case_lock);
end;
$$;

create or replace function public.request_payment_milestone(
	p_payment_milestone_id uuid,
	p_lock_version bigint
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
	v_actor uuid := (select auth.uid());
	v_case public.fulfilment_cases%rowtype;
	v_milestone public.payment_milestones%rowtype;
	v_case_id uuid;
	v_case_lock bigint;
begin
	if v_actor is null or not (select private.has_any_role(array['owner', 'admin', 'sales']::text[])) then raise exception using errcode = '42501', message = 'CRM role required'; end if;
	select fulfilment_case_id into v_case_id from public.payment_milestones where id = p_payment_milestone_id;
	if not found then raise exception using errcode = 'P0002', message = 'PaymentMilestone not found'; end if;
	select * into v_case from public.fulfilment_cases where id = v_case_id for update;
	select * into v_milestone from public.payment_milestones where id = p_payment_milestone_id for update;
	if v_case.status <> 'open' then raise exception using errcode = '55000', message = 'Closed FulfilmentCases are read-only'; end if;
	if v_milestone.status = 'awaiting' then
		return jsonb_build_object('payment_milestone_id', v_milestone.id, 'status', v_milestone.status, 'lock_version', v_milestone.lock_version, 'fulfilment_case_lock_version', v_case.lock_version, 'idempotent', true);
	end if;
	if v_milestone.status <> 'not_due' then raise exception using errcode = '22023', message = 'Only not-due milestones can be requested'; end if;
	if v_milestone.lock_version is distinct from p_lock_version then raise exception using errcode = '40001', message = 'Stale PaymentMilestone lock_version'; end if;
	update public.payment_milestones
	set status = 'awaiting', requested_at = coalesce(requested_at, now()), lock_version = lock_version + 1
	where id = p_payment_milestone_id and lock_version = p_lock_version
	returning * into v_milestone;
	update public.fulfilment_cases set lock_version = lock_version + 1 where id = v_case.id returning lock_version into v_case_lock;
	insert into public.activities (lead_id, client_id, quote_id, fulfilment_case_id, actor_id, event_type, metadata, summary)
	values (v_case.lead_id, v_case.client_id, v_case.accepted_quote_id, v_case.id, v_actor, 'payment_milestone_requested', jsonb_build_object('payment_milestone_id', v_milestone.id, 'type', v_milestone.type), format('%s payment requested', initcap(replace(v_milestone.type, '_', ' '))));
	return jsonb_build_object('payment_milestone_id', v_milestone.id, 'status', v_milestone.status, 'lock_version', v_milestone.lock_version, 'fulfilment_case_lock_version', v_case_lock, 'idempotent', false);
end;
$$;

create or replace function public.record_payment_received(
	p_payment_milestone_id uuid,
	p_lock_version bigint,
	p_note text default null
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
	v_actor uuid := (select auth.uid());
	v_case public.fulfilment_cases%rowtype;
	v_milestone public.payment_milestones%rowtype;
	v_case_id uuid;
	v_case_lock bigint;
begin
	if v_actor is null or not (select private.has_any_role(array['owner', 'admin', 'sales']::text[])) then raise exception using errcode = '42501', message = 'CRM role required'; end if;
	select fulfilment_case_id into v_case_id from public.payment_milestones where id = p_payment_milestone_id;
	if not found then raise exception using errcode = 'P0002', message = 'PaymentMilestone not found'; end if;
	select * into v_case from public.fulfilment_cases where id = v_case_id for update;
	select * into v_milestone from public.payment_milestones where id = p_payment_milestone_id for update;
	if v_case.status <> 'open' then raise exception using errcode = '55000', message = 'Closed FulfilmentCases are read-only'; end if;
	if v_milestone.status = 'received' then
		return jsonb_build_object('payment_milestone_id', v_milestone.id, 'status', v_milestone.status, 'lock_version', v_milestone.lock_version, 'fulfilment_case_lock_version', v_case.lock_version, 'idempotent', true);
	end if;
	if v_milestone.status <> 'awaiting' then raise exception using errcode = '22023', message = 'Only awaiting milestones can be recorded as received'; end if;
	if v_milestone.lock_version is distinct from p_lock_version then raise exception using errcode = '40001', message = 'Stale PaymentMilestone lock_version'; end if;
	update public.payment_milestones
	set status = 'received', received_at = now(), received_recorded_by = v_actor, note = coalesce(nullif(trim(coalesce(p_note, '')), ''), note), lock_version = lock_version + 1
	where id = p_payment_milestone_id and lock_version = p_lock_version
	returning * into v_milestone;
	update public.fulfilment_cases set lock_version = lock_version + 1 where id = v_case.id returning lock_version into v_case_lock;
	insert into public.activities (lead_id, client_id, quote_id, fulfilment_case_id, actor_id, event_type, metadata, summary)
	values (v_case.lead_id, v_case.client_id, v_case.accepted_quote_id, v_case.id, v_actor, 'payment_milestone_received', jsonb_build_object('payment_milestone_id', v_milestone.id, 'type', v_milestone.type, 'received_at', v_milestone.received_at), format('%s payment recorded as received', initcap(replace(v_milestone.type, '_', ' '))));
	return jsonb_build_object('payment_milestone_id', v_milestone.id, 'status', v_milestone.status, 'received_at', v_milestone.received_at, 'received_recorded_by', v_milestone.received_recorded_by, 'lock_version', v_milestone.lock_version, 'fulfilment_case_lock_version', v_case_lock, 'idempotent', false);
end;
$$;

create or replace function public.mark_payment_not_required(
	p_payment_milestone_id uuid,
	p_lock_version bigint,
	p_note text default null
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
	v_actor uuid := (select auth.uid());
	v_case public.fulfilment_cases%rowtype;
	v_milestone public.payment_milestones%rowtype;
	v_case_id uuid;
	v_case_lock bigint;
begin
	if v_actor is null or not (select private.has_any_role(array['owner', 'admin', 'sales']::text[])) then raise exception using errcode = '42501', message = 'CRM role required'; end if;
	select fulfilment_case_id into v_case_id from public.payment_milestones where id = p_payment_milestone_id;
	if not found then raise exception using errcode = 'P0002', message = 'PaymentMilestone not found'; end if;
	select * into v_case from public.fulfilment_cases where id = v_case_id for update;
	select * into v_milestone from public.payment_milestones where id = p_payment_milestone_id for update;
	if v_case.status <> 'open' then raise exception using errcode = '55000', message = 'Closed FulfilmentCases are read-only'; end if;
	if v_milestone.status = 'not_required' then
		return jsonb_build_object('payment_milestone_id', v_milestone.id, 'status', v_milestone.status, 'lock_version', v_milestone.lock_version, 'fulfilment_case_lock_version', v_case.lock_version, 'idempotent', true);
	end if;
	if v_milestone.status <> 'not_due' then raise exception using errcode = '22023', message = 'Only not-due milestones can be marked not required'; end if;
	if v_milestone.lock_version is distinct from p_lock_version then raise exception using errcode = '40001', message = 'Stale PaymentMilestone lock_version'; end if;
	update public.payment_milestones
	set status = 'not_required', note = coalesce(nullif(trim(coalesce(p_note, '')), ''), note), lock_version = lock_version + 1
	where id = p_payment_milestone_id and lock_version = p_lock_version
	returning * into v_milestone;
	update public.fulfilment_cases set lock_version = lock_version + 1 where id = v_case.id returning lock_version into v_case_lock;
	insert into public.activities (lead_id, client_id, quote_id, fulfilment_case_id, actor_id, event_type, metadata, summary)
	values (v_case.lead_id, v_case.client_id, v_case.accepted_quote_id, v_case.id, v_actor, 'payment_milestone_marked_not_required', jsonb_build_object('payment_milestone_id', v_milestone.id, 'type', v_milestone.type), format('%s payment marked not required', initcap(replace(v_milestone.type, '_', ' '))));
	return jsonb_build_object('payment_milestone_id', v_milestone.id, 'status', v_milestone.status, 'lock_version', v_milestone.lock_version, 'fulfilment_case_lock_version', v_case_lock, 'idempotent', false);
end;
$$;

create or replace function public.correct_payment_milestone(
	p_payment_milestone_id uuid,
	p_lock_version bigint,
	p_status text,
	p_reason text,
	p_note text default null
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
	v_actor uuid := (select auth.uid());
	v_case public.fulfilment_cases%rowtype;
	v_milestone public.payment_milestones%rowtype;
	v_case_id uuid;
	v_case_lock bigint;
	v_reason text := nullif(trim(coalesce(p_reason, '')), '');
	v_old_status text;
begin
	if v_actor is null or not (select private.has_any_role(array['owner', 'admin']::text[])) then raise exception using errcode = '42501', message = 'Owner or admin role required'; end if;
	perform private.require_current_session_aal2();
	if p_status not in ('awaiting', 'received', 'not_required') then raise exception using errcode = '22023', message = 'Invalid corrected PaymentMilestone status'; end if;
	if v_reason is null then raise exception using errcode = '22023', message = 'Payment correction reason is required'; end if;
	select fulfilment_case_id into v_case_id from public.payment_milestones where id = p_payment_milestone_id;
	if not found then raise exception using errcode = 'P0002', message = 'PaymentMilestone not found'; end if;
	select * into v_case from public.fulfilment_cases where id = v_case_id for update;
	select * into v_milestone from public.payment_milestones where id = p_payment_milestone_id for update;
	if v_case.status <> 'open' then raise exception using errcode = '55000', message = 'Closed FulfilmentCases are read-only'; end if;
	if v_milestone.lock_version is distinct from p_lock_version then raise exception using errcode = '40001', message = 'Stale PaymentMilestone lock_version'; end if;
	v_old_status := v_milestone.status;
	if p_status = 'received' then
		if v_milestone.status <> 'received' then raise exception using errcode = '22023', message = 'Only received evidence can be corrected as received'; end if;
		update public.payment_milestones
		set note = coalesce(nullif(trim(coalesce(p_note, '')), ''), note), lock_version = lock_version + 1
		where id = p_payment_milestone_id and lock_version = p_lock_version
		returning * into v_milestone;
	elsif p_status = 'awaiting' then
		if v_milestone.status not in ('received', 'not_required') then raise exception using errcode = '22023', message = 'Only received or waived evidence can be corrected to awaiting'; end if;
		update public.payment_milestones
		set status = 'awaiting', requested_at = coalesce(requested_at, now()), received_at = null, received_recorded_by = null, note = coalesce(nullif(trim(coalesce(p_note, '')), ''), note), lock_version = lock_version + 1
		where id = p_payment_milestone_id and lock_version = p_lock_version
		returning * into v_milestone;
	else
		if v_milestone.status not in ('awaiting', 'received', 'not_required') then raise exception using errcode = '22023', message = 'Payment evidence cannot be corrected from its current state'; end if;
		update public.payment_milestones
		set status = 'not_required', received_at = null, received_recorded_by = null, note = coalesce(nullif(trim(coalesce(p_note, '')), ''), note), lock_version = lock_version + 1
		where id = p_payment_milestone_id and lock_version = p_lock_version
		returning * into v_milestone;
	end if;
	update public.fulfilment_cases set lock_version = lock_version + 1 where id = v_case.id returning lock_version into v_case_lock;
	insert into public.activities (lead_id, client_id, quote_id, fulfilment_case_id, actor_id, event_type, metadata, summary)
	values (v_case.lead_id, v_case.client_id, v_case.accepted_quote_id, v_case.id, v_actor, 'payment_milestone_corrected', jsonb_build_object('payment_milestone_id', v_milestone.id, 'from_status', v_old_status, 'to_status', v_milestone.status, 'reason', v_reason), 'Payment milestone corrected');
	perform private.record_security_audit('payment_milestone_corrected', 'payment_milestone', v_milestone.id::text, jsonb_build_object('from_status', v_old_status, 'to_status', v_milestone.status, 'reason', v_reason));
	return jsonb_build_object('payment_milestone_id', v_milestone.id, 'status', v_milestone.status, 'lock_version', v_milestone.lock_version, 'fulfilment_case_lock_version', v_case_lock);
end;
$$;

create or replace function public.complete_fulfilment(
	p_fulfilment_case_id uuid,
	p_lock_version bigint
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
	v_actor uuid := (select auth.uid());
	v_case public.fulfilment_cases%rowtype;
	v_case_lock bigint;
	v_payment_count integer;
	v_has_successful_step boolean;
	v_has_incomplete_step boolean;
	v_has_unready_payment boolean;
begin
	if v_actor is null or not (select private.has_any_role(array['owner', 'admin', 'sales']::text[])) then raise exception using errcode = '42501', message = 'CRM role required'; end if;
	select * into v_case from public.fulfilment_cases where id = p_fulfilment_case_id for update;
	if not found then raise exception using errcode = 'P0002', message = 'FulfilmentCase not found'; end if;
	if v_case.status = 'completed' then
		return jsonb_build_object('fulfilment_case_id', v_case.id, 'status', v_case.status, 'lock_version', v_case.lock_version, 'idempotent', true);
	end if;
	if v_case.status <> 'open' then raise exception using errcode = '55000', message = 'Cancelled FulfilmentCases cannot be completed'; end if;
	if v_case.lock_version is distinct from p_lock_version then raise exception using errcode = '40001', message = 'Stale FulfilmentCase lock_version'; end if;
	select count(*)::integer into v_payment_count from public.payment_milestones where fulfilment_case_id = v_case.id;
	select exists (
		select 1 from public.fulfilment_steps
		where fulfilment_case_id = v_case.id
			and status in ('completed', 'delivered', 'collected')
	) into v_has_successful_step;
	select exists (
		select 1 from public.fulfilment_steps
		where fulfilment_case_id = v_case.id
			and status not in ('completed', 'delivered', 'collected', 'cancelled')
	) into v_has_incomplete_step;
	select exists (
		select 1 from public.payment_milestones
		where fulfilment_case_id = v_case.id
			and status not in ('received', 'not_required')
	) into v_has_unready_payment;
	if not v_has_successful_step then raise exception using errcode = '55000', message = 'FulfilmentCase requires a successful non-cancelled step'; end if;
	if v_has_incomplete_step then raise exception using errcode = '55000', message = 'All non-cancelled FulfilmentSteps must be successful'; end if;
	if v_payment_count <> 2 or v_has_unready_payment then raise exception using errcode = '55000', message = 'All required PaymentMilestones must be received or not required'; end if;
	update public.fulfilment_cases
	set status = 'completed', completed_at = now(), lock_version = lock_version + 1
	where id = v_case.id and lock_version = p_lock_version
	returning lock_version into v_case_lock;
	if v_case_lock is null then raise exception using errcode = '40001', message = 'FulfilmentCase changed during completion'; end if;
	insert into public.activities (lead_id, client_id, quote_id, fulfilment_case_id, actor_id, event_type, metadata, summary)
	values (v_case.lead_id, v_case.client_id, v_case.accepted_quote_id, v_case.id, v_actor, 'fulfilment_completed', jsonb_build_object('completed_at', now()), 'Fulfilment case completed');
	return jsonb_build_object('fulfilment_case_id', v_case.id, 'status', 'completed', 'completed_at', now(), 'lock_version', v_case_lock, 'idempotent', false);
end;
$$;

create or replace function public.cancel_fulfilment(
	p_fulfilment_case_id uuid,
	p_lock_version bigint,
	p_reason text
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
	v_actor uuid := (select auth.uid());
	v_case public.fulfilment_cases%rowtype;
	v_reason text := nullif(trim(coalesce(p_reason, '')), '');
	v_case_lock bigint;
begin
	if v_actor is null or not (select private.has_any_role(array['owner', 'admin']::text[])) then raise exception using errcode = '42501', message = 'Owner or admin role required'; end if;
	perform private.require_current_session_aal2();
	if v_reason is null then raise exception using errcode = '22023', message = 'Fulfilment cancellation reason is required'; end if;
	select * into v_case from public.fulfilment_cases where id = p_fulfilment_case_id for update;
	if not found then raise exception using errcode = 'P0002', message = 'FulfilmentCase not found'; end if;
	if v_case.status = 'cancelled' then
		return jsonb_build_object('fulfilment_case_id', v_case.id, 'status', v_case.status, 'lock_version', v_case.lock_version, 'idempotent', true);
	end if;
	if v_case.status <> 'open' then raise exception using errcode = '22023', message = 'Completed FulfilmentCases cannot be cancelled'; end if;
	if v_case.lock_version is distinct from p_lock_version then raise exception using errcode = '40001', message = 'Stale FulfilmentCase lock_version'; end if;
	update public.fulfilment_cases
	set status = 'cancelled', cancelled_at = now(), cancel_reason = v_reason, lock_version = lock_version + 1
	where id = v_case.id and lock_version = p_lock_version
	returning lock_version into v_case_lock;
	if v_case_lock is null then raise exception using errcode = '40001', message = 'FulfilmentCase changed during cancellation'; end if;
	insert into public.activities (lead_id, client_id, quote_id, fulfilment_case_id, actor_id, event_type, metadata, summary)
	values (v_case.lead_id, v_case.client_id, v_case.accepted_quote_id, v_case.id, v_actor, 'fulfilment_cancelled', jsonb_build_object('reason', v_reason), 'Fulfilment case cancelled');
	perform private.record_security_audit('fulfilment_cancelled', 'fulfilment_case', v_case.id::text, jsonb_build_object('reason', v_reason));
	return jsonb_build_object('fulfilment_case_id', v_case.id, 'status', 'cancelled', 'cancelled_at', now(), 'lock_version', v_case_lock);
end;
$$;

revoke all on function public.start_lead_qualification(uuid, bigint, text) from public, anon;
grant execute on function public.start_lead_qualification(uuid, bigint, text) to authenticated;
revoke all on function public.ready_lead_for_quote(uuid, bigint, text) from public, anon;
grant execute on function public.ready_lead_for_quote(uuid, bigint, text) to authenticated;
revoke all on function public.create_fulfilment_case_for_accepted_quote(uuid) from public, anon, authenticated;
grant execute on function public.create_fulfilment_case_for_accepted_quote(uuid) to service_role;
revoke all on function public.create_fulfilment_step(uuid, text, bigint, text, text) from public, anon;
grant execute on function public.create_fulfilment_step(uuid, text, bigint, text, text) to authenticated;
revoke all on function public.schedule_fulfilment_step(uuid, bigint, timestamptz) from public, anon;
grant execute on function public.schedule_fulfilment_step(uuid, bigint, timestamptz) to authenticated;
revoke all on function public.reschedule_fulfilment_step(uuid, bigint, timestamptz) from public, anon;
grant execute on function public.reschedule_fulfilment_step(uuid, bigint, timestamptz) to authenticated;
revoke all on function public.complete_fulfilment_step(uuid, bigint) from public, anon;
grant execute on function public.complete_fulfilment_step(uuid, bigint) to authenticated;
revoke all on function public.cancel_fulfilment_step(uuid, bigint, text) from public, anon;
grant execute on function public.cancel_fulfilment_step(uuid, bigint, text) to authenticated;
revoke all on function public.request_payment_milestone(uuid, bigint) from public, anon;
grant execute on function public.request_payment_milestone(uuid, bigint) to authenticated;
revoke all on function public.record_payment_received(uuid, bigint, text) from public, anon;
grant execute on function public.record_payment_received(uuid, bigint, text) to authenticated;
revoke all on function public.mark_payment_not_required(uuid, bigint, text) from public, anon;
grant execute on function public.mark_payment_not_required(uuid, bigint, text) to authenticated;
revoke all on function public.correct_payment_milestone(uuid, bigint, text, text, text) from public, anon;
grant execute on function public.correct_payment_milestone(uuid, bigint, text, text, text) to authenticated;
revoke all on function public.complete_fulfilment(uuid, bigint) from public, anon;
grant execute on function public.complete_fulfilment(uuid, bigint) to authenticated;
revoke all on function public.cancel_fulfilment(uuid, bigint, text) from public, anon;
grant execute on function public.cancel_fulfilment(uuid, bigint, text) to authenticated;
revoke all on function public.create_task(uuid, uuid, uuid, text, text, text, uuid, timestamptz, text) from public, anon;
revoke all on function public.create_task(uuid, uuid, uuid, uuid, text, text, text, uuid, timestamptz, text) from public, anon;
grant execute on function public.create_task(uuid, uuid, uuid, text, text, text, uuid, timestamptz, text) to authenticated;
grant execute on function public.create_task(uuid, uuid, uuid, uuid, text, text, text, uuid, timestamptz, text) to authenticated;

comment on function public.create_fulfilment_case_for_accepted_quote(uuid) is 'Internal service-role handoff helper; normal case creation is part of trusted Quote acceptance.';
comment on function public.create_fulfilment_step(uuid, text, bigint, text, text) is 'Trusted FulfilmentStep creation with one active step per type.';
comment on function public.complete_fulfilment(uuid, bigint) is 'Trusted completion guard requiring successful work and settled CRM milestones.';
comment on function public.cancel_fulfilment(uuid, bigint, text) is 'AAL2 Owner/Admin FulfilmentCase cancellation with audit evidence.';

commit;
