export const trustedEnvironmentKeys = [
	'SUPABASE_URL',
	'SUPABASE_SERVICE_ROLE_KEY',
	'SENDPULSE_CLIENT_ID',
	'SENDPULSE_CLIENT_SECRET',
	'SENDPULSE_API_BASE_URL',
	'SENDPULSE_SENDER_EMAIL',
	'SENDPULSE_SENDER_NAME',
	'SENDPULSE_WEBHOOK_SECRET',
	'SENDPULSE_SENDER_DOMAIN',
	'SENDPULSE_DKIM_SELECTOR',
	'SENDPULSE_SPF_RECORD',
	'SENDPULSE_DKIM_RECORD',
	'SENDPULSE_DMARC_RECORD',
	'SENDPULSE_DOMAIN_AUTHENTICATED',
	'AUTOMATION_CRON_SECRET',
	'BRICKS_FORM_ID',
	'BRICKS_WEBHOOK_SECRET'
] as const;

export { parsePublicEnv } from './public-env';
export type { PublicEnvironment } from './public-env';
